sonar.projectKey=ton_organisation_tonprojet
sonar.organization=ton_organisation

sonar.projectName=Symfony Fork (Quality Check)
sonar.projectVersion=1.0

# Répertoires analysés
sonar.sources=src

# Répertoires de tests
sonar.tests=tests

# Langages principaux
sonar.language=php

# Exclusions spécifiques (si besoin)
sonar.exclusions=vendor/**,var/**

# Couverture si tu en as
sonar.php.coverage.reportPaths=coverage.xml
