sonar.projectKey=RomainNgd_symfony
sonar.organization=romainngd

sonar.projectName=Symfony Fork (Quality Check)
sonar.projectVersion=1.0

# Répertoires analysés
sonar.sources=src/Symfony

sonar.tests=Tests,tests

# Langages principaux
sonar.language=php

# Exclusions spécifiques (si besoin)
sonar.exclusions=**/Resources/**/*, **/Fixtures/**/*, vendor/**, var/**
sonar.security.exclusions=**/Tests/**,**/tests/**,**/*Test.php
sonar.reliability.exclusions=**/Tests/**,**/tests/**,**/*Test.php


# Couverture si tu en as
sonar.php.coverage.reportPaths=coverage.xml
